"""Add details column to TimelineEvent

Revision ID: 05771aaafee2
Revises: 573697f1687a
Create Date: 2025-02-01 21:56:17.683040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05771aaafee2'
down_revision = '573697f1687a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_event', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
